# Numpy

In [1]:
import numpy as np

In [2]:
a = np.array([2, 3, 4]) # 1-dimensional array
a


array([2, 3, 4])

In [7]:
b = np.array([2, 3, 4, 5, 6, 7]).reshape(2, 3) # 2-dimensional array
b

array([[2, 3, 4],
       [5, 6, 7]])

In [13]:
c = np.array([2, 3, 4, 5, 6, 7, 8, 9]).reshape(2, 2, 2)
c

array([[[2, 3],
        [4, 5]],

       [[6, 7],
        [8, 9]]])

## Numpy Calculations

In [17]:
d = np.array([2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13])

d.sum()
d.min()
d.max()
d.mean()

7.5

## Special Numpy Arrays

In [27]:
np.zeros(6) # create an array of 6 zeros
np.linspace(0, 6, 10) # Creates an array of values from 0 through 6 in 10 even spaces
np.random.rand(3) # Three random values between 0 and 1
np.random.randint(1, 1000) # A random integer between 1 and 1000
np.arange(25) # gives you a range of integers between 1 - 25

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])